#!/bin/sh

pip install --upgrade src/we_panic_utils/
python src/run_model.py 3D-CNN frames \
--kfold 4 
--csv wepanic_collated_catalogue.csv \
--output_dir run_history/test_cnn \
--epochs 1 \
--steps_per_epoch 100 \
--batch_size 14 \
