#!/bin/sh

usage(){
echo 'setup DEEPLEARNINGCLASSDATA_CSV_LOC VIDEO_DIR'
exit
}

python src/scripts/info_extraction/collate_data.py $1
python src/scripts/info_extraction/extract_frames.py $2 --resize_dims 32 32

