#!/bin/sh

## script for runs on the cloud

pip install --upgrade src/we_panic_utils/

python src/run_model.py BN_CNN_3D_DO picky_32_32 \
--features hr \
--csv wepanic_collated_catalogue.csv \
--output_dir run_history/TEST \
--epochs 15 \
--dimensions 32 32 \
--steps_per_epoch 500 \
--batch_size 14 \
--greyscale_on \
--kfold 5 \
--loss mean_squared_error \
--sequence_length 60 \
--cyclic_lr triangular_lr 0.0001 0.006 105000 
